<Project>

    <PropertyGroup>
        <Version>0.4.0-beta</Version>
    </PropertyGroup>

    <PropertyGroup Condition="'$(PackageReleaseVersion)' != '' and '$(MSBuildProjectName)' != 'FIO'">
        <Version>$(PackageReleaseVersion)</Version>
    </PropertyGroup>

    <PropertyGroup>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <PropertyGroup>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>

    <PropertyGroup>
        <Authors>Daniel Larsen</Authors>
        <Copyright>Copyright (c) 2022-2026 Daniel Larsen</Copyright>
        <RepositoryUrl>https://github.com/fs-fio/fio</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageProjectUrl>https://github.com/fs-fio/fio</PackageProjectUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
        <PackageIcon>logo.png</PackageIcon>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <DebugType>embedded</DebugType>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
    </PropertyGroup>

    <PropertyGroup>
        <DisableImplicitFSharpCoreReference>true</DisableImplicitFSharpCoreReference>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FSharp.Core" />
    </ItemGroup>

</Project>
